/*
	visualise_partisan_bigram_examples_by_topic.do
	
	> Reads in examples of highly-partisan bigrams that have a significantly higher probability of being spoken when 
	God has been evoked, grouped by topic for each party (generated by 
	"identify_partisan_bigram_examples_by_topic.py").
	
	> Gnerates bar graphs that compares these bigrams' probabilities / confidence intervals in God speeches and non-God 
	speeches by Republicans (Figure 2) and Democrats (Figure 3)

*/


clear all
set more off
cls

grstyle init
grstyle set plain, horizontal grid

cd "C:\Users\Anthony\Documents\Projects\rtalk\data"


// Create bar graphs for Republican example bigrams, grouped by topic  (Figure 2) //

*import rep prob data by topic
use "rep_prob_data_by_topic.dta", clear
rename (nogod_mean nogod_se nogod_lb nogod_ub god_mean god_se god_lb god_ub) (prob0 prob_se0 prob_lb0 prob_ub0 prob1 prob_se1 prob_lb1 prob_ub1)
reshape long prob prob_se prob_lb prob_ub, i(phrase) j(god)

*rescale to % 
g prob_pct = 100*prob
g prob_se_pct = 100*prob_se
g prob_ub_pct = 100*prob_ub
g prob_lb_pct = 100*prob_lb
drop prob prob_se prob_ub prob_lb
rename (prob_pct prob_se_pct prob_ub_pct prob_lb_pct) (prob prob_se prob_ub prob_lb)

*create difference between prob in god corpus and prob in rest of corpus to sort bars
bysort phrase (god): g prob_nogod = prob[1]
bysort phrase (god): g prob_god = prob[2]
g prob_diff = prob_god - prob_nogod

*generate phrase_order which is the order of the bars over phrases, and yaxis values to place bars
bysort topic god: egen phrase_order = rank(prob_diff) 
g yaxis = god + (phrase_order-1)*3 + 1

sort topic prob_diff god 

*topic graph: war on terror
bro if topic=="war_on_terror"
graph twoway	(bar prob yaxis if phrase_order==1 & god==0 & topic=="war_on_terror", horizontal bcolor("255 124 128")) ///
				(bar prob yaxis if phrase_order==1 & god==1 & topic=="war_on_terror", horizontal bcolor(red))  ///
				(bar prob yaxis if phrase_order==2 & god==0 & topic=="war_on_terror", horizontal bcolor("255 124 128")) ///
				(bar prob yaxis if phrase_order==2 & god==1 & topic=="war_on_terror", horizontal bcolor(red)) ///
				(bar prob yaxis if phrase_order==3 & god==0 & topic=="war_on_terror", horizontal bcolor("255 124 128")) ///
				(bar prob yaxis if phrase_order==3 & god==1 & topic=="war_on_terror", horizontal bcolor(red)) ///
				(bar prob yaxis if phrase_order==4 & god==0 & topic=="war_on_terror", horizontal bcolor("255 124 128")) ///
				(bar prob yaxis if phrase_order==4 & god==1 & topic=="war_on_terror", horizontal bcolor(red)) ///
				(bar prob yaxis if phrase_order==5 & god==0 & topic=="war_on_terror", horizontal bcolor("255 124 128")) ///
				(bar prob yaxis if phrase_order==5 & god==1 & topic=="war_on_terror", horizontal bcolor(red)) ///
				(rcap prob_ub prob_lb yaxis if topic=="war_on_terror", horizontal lcolor(gs7)), ///
				ylabel( 1.5 "radic_islam" 4.5 "bin_laden" 7.5 "terrorist_attack" 10.5 "al_qaeda"  13.5 "war_terror" , noticks labgap(*3)) ytitle("") ///
				  legend(order(2 `"Republican "God" Speeches"' 1 "Other Republican Speeches") size(vsmall)) xtitle("Phrase Probability (%)") title("War on Terror") name("war_on_terror", replace)

*topic graph: defense
bro if topic=="defense"
graph twoway	(bar prob yaxis if phrase_order==1 & god==0 & topic=="defense", horizontal bcolor("255 124 128")) ///
				(bar prob yaxis if phrase_order==1 & god==1 & topic=="defense", horizontal bcolor(red))  ///
				(bar prob yaxis if phrase_order==2 & god==0 & topic=="defense", horizontal bcolor("255 124 128")) ///
				(bar prob yaxis if phrase_order==2 & god==1 & topic=="defense", horizontal bcolor(red)) ///
				(bar prob yaxis if phrase_order==3 & god==0 & topic=="defense", horizontal bcolor("255 124 128")) ///
				(bar prob yaxis if phrase_order==3 & god==1 & topic=="defense", horizontal bcolor(red)) ///
				(bar prob yaxis if phrase_order==4 & god==0 & topic=="defense", horizontal bcolor("255 124 128")) ///
				(bar prob yaxis if phrase_order==4 & god==1 & topic=="defense", horizontal bcolor(red)) ///
				(bar prob yaxis if phrase_order==5 & god==0 & topic=="defense", horizontal bcolor("255 124 128")) ///
				(bar prob yaxis if phrase_order==5 & god==1 & topic=="defense", horizontal bcolor(red)) ///
				(rcap prob_ub prob_lb yaxis if topic=="defense", horizontal lcolor(gs7)), ///
				ylabel( 1.5 "send_troop" 4.5 "ballist_missil" 7.5 "nation_defens" 10.5 "air_forc"  13.5 "arm_forc" , noticks labgap(*3)) ytitle("") ///
				  legend(order(2 `"Republican "God" Speeches"' 1 "Other Republican Speeches") size(vsmall)) xtitle("Phrase Probability (%)") title("Defense") name("defense", replace)

*topic graph: immigration
bro if topic=="immigration"
format prob %9.1f
graph twoway	(bar prob yaxis if phrase_order==1 & god==0 & topic=="immigration", horizontal bcolor("255 124 128")) ///
				(bar prob yaxis if phrase_order==1 & god==1 & topic=="immigration", horizontal bcolor(red))  ///
				(bar prob yaxis if phrase_order==2 & god==0 & topic=="immigration", horizontal bcolor("255 124 128")) ///
				(bar prob yaxis if phrase_order==2 & god==1 & topic=="immigration", horizontal bcolor(red)) ///
				(bar prob yaxis if phrase_order==3 & god==0 & topic=="immigration", horizontal bcolor("255 124 128")) ///
				(bar prob yaxis if phrase_order==3 & god==1 & topic=="immigration", horizontal bcolor(red)) ///
				(bar prob yaxis if phrase_order==4 & god==0 & topic=="immigration", horizontal bcolor("255 124 128")) ///
				(bar prob yaxis if phrase_order==4 & god==1 & topic=="immigration", horizontal bcolor(red)) ///
				(bar prob yaxis if phrase_order==5 & god==0 & topic=="immigration", horizontal bcolor("255 124 128")) ///
				(bar prob yaxis if phrase_order==5 & god==1 & topic=="immigration", horizontal bcolor(red)) ///
				(rcap prob_ub prob_lb yaxis if topic=="immigration", horizontal lcolor(gs7)), ///
				ylabel( 1.5 "control_border" 4.5 "illeg_alien" 7.5 "secur_border" 10.5 "border_patrol"  13.5 "illeg_immigr" , noticks labgap(*3)) ytitle("") ///
				  legend(order(2 `"Republican "God" Speeches"' 1 "Other Republican Speeches") size(vsmall)) xtitle("Phrase Probability (%)") title("Immigration") name("immigration", replace)
				 		 
*topic graph: role_of_state
bro if topic=="role_of_state"
format prob %9.1f
graph twoway	(bar prob yaxis if phrase_order==1 & god==0 & topic=="role_of_state", horizontal bcolor("255 124 128")) ///
				(bar prob yaxis if phrase_order==1 & god==1 & topic=="role_of_state", horizontal bcolor(red))  ///
				(bar prob yaxis if phrase_order==2 & god==0 & topic=="role_of_state", horizontal bcolor("255 124 128")) ///
				(bar prob yaxis if phrase_order==2 & god==1 & topic=="role_of_state", horizontal bcolor(red)) ///
				(bar prob yaxis if phrase_order==3 & god==0 & topic=="role_of_state", horizontal bcolor("255 124 128")) ///
				(bar prob yaxis if phrase_order==3 & god==1 & topic=="role_of_state", horizontal bcolor(red)) ///
				(bar prob yaxis if phrase_order==4 & god==0 & topic=="role_of_state", horizontal bcolor("255 124 128")) ///
				(bar prob yaxis if phrase_order==4 & god==1 & topic=="role_of_state", horizontal bcolor(red)) ///
				(bar prob yaxis if phrase_order==5 & god==0 & topic=="role_of_state", horizontal bcolor("255 124 128")) ///
				(bar prob yaxis if phrase_order==5 & god==1 & topic=="role_of_state", horizontal bcolor(red)) ///
				(rcap prob_ub prob_lb yaxis if topic=="role_of_state", horizontal lcolor(gs7)), ///
				ylabel( 1.5 "tax_burden" 4.5 "lower_tax" 7.5 "tax_relief" 10.5 "limit_govern"  13.5 "big_govern" , noticks labgap(*3)) ytitle("") ///
				  legend(order(2 `"Republican "God" Speeches"' 1 "Other Republican Speeches") size(vsmall)) xtitle("Phrase Probability (%)") title("Role of State") name("role_of_state", replace)

*topic graph: abortion
bro if topic=="abortion"
format prob %9.1f
graph twoway	(bar prob yaxis if phrase_order==1 & god==0 & topic=="abortion", horizontal bcolor("255 124 128")) ///
				(bar prob yaxis if phrase_order==1 & god==1 & topic=="abortion", horizontal bcolor(red))  ///
				(bar prob yaxis if phrase_order==2 & god==0 & topic=="abortion", horizontal bcolor("255 124 128")) ///
				(bar prob yaxis if phrase_order==2 & god==1 & topic=="abortion", horizontal bcolor(red)) ///
				(bar prob yaxis if phrase_order==3 & god==0 & topic=="abortion", horizontal bcolor("255 124 128")) ///
				(bar prob yaxis if phrase_order==3 & god==1 & topic=="abortion", horizontal bcolor(red)) ///
				(bar prob yaxis if phrase_order==4 & god==0 & topic=="abortion", horizontal bcolor("255 124 128")) ///
				(bar prob yaxis if phrase_order==4 & god==1 & topic=="abortion", horizontal bcolor(red)) ///
				(bar prob yaxis if phrase_order==5 & god==0 & topic=="abortion", horizontal bcolor("255 124 128")) ///
				(bar prob yaxis if phrase_order==5 & god==1 & topic=="abortion", horizontal bcolor(red)) ///
				(rcap prob_ub prob_lb yaxis if topic=="abortion", horizontal lcolor(gs7)), ///
				ylabel( 1.5 "innoc_unborn" 4.5 "unborn_babi" 7.5 "innoc_human" 10.5 "birth_abort"  13.5 "unborn_children" , noticks labgap(*3)) ytitle("") ///
				  legend(order(2 `"Republican "God" Speeches"' 1 "Other Republican Speeches") size(vsmall)) xtitle("Phrase Probability (%)") title("Abortion") name("abortion", replace)

*topic graph: communism
bro if topic=="communism"
format prob %9.1f
graph twoway	(bar prob yaxis if phrase_order==1 & god==0 & topic=="communism", horizontal bcolor("255 124 128")) ///
				(bar prob yaxis if phrase_order==1 & god==1 & topic=="communism", horizontal bcolor(red))  ///
				(bar prob yaxis if phrase_order==2 & god==0 & topic=="communism", horizontal bcolor("255 124 128")) ///
				(bar prob yaxis if phrase_order==2 & god==1 & topic=="communism", horizontal bcolor(red)) ///
				(bar prob yaxis if phrase_order==3 & god==0 & topic=="communism", horizontal bcolor("255 124 128")) ///
				(bar prob yaxis if phrase_order==3 & god==1 & topic=="communism", horizontal bcolor(red)) ///
				(bar prob yaxis if phrase_order==4 & god==0 & topic=="communism", horizontal bcolor("255 124 128")) ///
				(bar prob yaxis if phrase_order==4 & god==1 & topic=="communism", horizontal bcolor(red)) ///
				(bar prob yaxis if phrase_order==5 & god==0 & topic=="communism", horizontal bcolor("255 124 128")) ///
				(bar prob yaxis if phrase_order==5 & god==1 & topic=="communism", horizontal bcolor(red)) ///
				(rcap prob_ub prob_lb yaxis if topic=="communism", horizontal lcolor(gs7)), ///
				ylabel( 1.5 "communist_govern" 4.5 "communist_china" 7.5 "communist_regim" 10.5 "red_china"  13.5 "communist_parti" , noticks labgap(*3)) ytitle("") ///
				  legend(order(2 `"Republican "God" Speeches"' 1 "Other Republican Speeches") size(vsmall)) xtitle("Phrase Probability (%)") title("Communism") name("communism", replace)


*topic graph: narcotics
bro if topic=="narcotics"
format prob %9.1f
graph twoway	(bar prob yaxis if phrase_order==1 & god==0 & topic=="narcotics", horizontal bcolor("255 124 128")) ///
				(bar prob yaxis if phrase_order==1 & god==1 & topic=="narcotics", horizontal bcolor(red))  ///
				(bar prob yaxis if phrase_order==2 & god==0 & topic=="narcotics", horizontal bcolor("255 124 128")) ///
				(bar prob yaxis if phrase_order==2 & god==1 & topic=="narcotics", horizontal bcolor(red)) ///
				(bar prob yaxis if phrase_order==3 & god==0 & topic=="narcotics", horizontal bcolor("255 124 128")) ///
				(bar prob yaxis if phrase_order==3 & god==1 & topic=="narcotics", horizontal bcolor(red)) ///
				(bar prob yaxis if phrase_order==4 & god==0 & topic=="narcotics", horizontal bcolor("255 124 128")) ///
				(bar prob yaxis if phrase_order==4 & god==1 & topic=="narcotics", horizontal bcolor(red)) ///
				(bar prob yaxis if phrase_order==5 & god==0 & topic=="narcotics", horizontal bcolor("255 124 128")) ///
				(bar prob yaxis if phrase_order==5 & god==1 & topic=="narcotics", horizontal bcolor(red)) ///
				(rcap prob_ub prob_lb yaxis if topic=="narcotics", horizontal lcolor(gs7)), ///
				ylabel( 1.5 "drug_smuggler" 4.5 "drug_traffick" 7.5 "drug_use" 10.5 "drug_dealer"  13.5 "illeg_drug" , noticks labgap(*3)) ytitle("") ///
				  legend(order(2 `"Republican "God" Speeches"' 1 "Other Republican Speeches") size(vsmall)) xtitle("Phrase Probability (%)") title("Narcotics") name("narcotics", replace)				  
	

*graph options (choose 6 from these in this order): war_on_terror defense immigration role_of_state abortion communism narcotics
grc1leg war_on_terror defense immigration role_of_state abortion communism, col(3) name(rep_phrase_probs, replace)

*save graph 
graph export rep_phrase_probs.eps, name(rep_phrase_probs) replace
graph drop war_on_terror defense immigration role_of_state abortion communism narcotics


// Create bar graphs for Democrat example bigrams, grouped by topic  (Figure 3) //

*import dem prob data by topic
use "dem_prob_data_by_topic.dta", clear
rename (nogod_mean nogod_se nogod_lb nogod_ub god_mean god_se god_lb god_ub) (prob0 prob_se0 prob_lb0 prob_ub0 prob1 prob_se1 prob_lb1 prob_ub1)
reshape long prob prob_se prob_lb prob_ub, i(phrase) j(god)

*rescale to % 
g prob_pct = 100*prob
g prob_se_pct = 100*prob_se
g prob_ub_pct = 100*prob_ub
g prob_lb_pct = 100*prob_lb
drop prob prob_se prob_ub prob_lb
rename (prob_pct prob_se_pct prob_ub_pct prob_lb_pct) (prob prob_se prob_ub prob_lb)

*create difference between prob in god corpus and prob in rest of corpus to sort bars
bysort phrase (god): g prob_nogod = prob[1]
bysort phrase (god): g prob_god = prob[2]
g prob_diff = prob_god - prob_nogod

*generate phrase_order which is the order of the bars over phrases, and yaxis values to place bars
bysort topic god: egen phrase_order = rank(prob_diff) 
g yaxis = god + (phrase_order-1)*3 + 1

sort topic prob_diff god 

*topic graph: healthcare
bro if topic=="healthcare"
graph twoway	(bar prob yaxis if phrase_order==1 & god==0 & topic=="healthcare", horizontal bcolor(eltblue)) ///
				(bar prob yaxis if phrase_order==1 & god==1 & topic=="healthcare", horizontal bcolor(blue))  ///
				(bar prob yaxis if phrase_order==2 & god==0 & topic=="healthcare", horizontal bcolor(eltblue)) ///
				(bar prob yaxis if phrase_order==2 & god==1 & topic=="healthcare", horizontal bcolor(blue)) ///
				(bar prob yaxis if phrase_order==3 & god==0 & topic=="healthcare", horizontal bcolor(eltblue)) ///
				(bar prob yaxis if phrase_order==3 & god==1 & topic=="healthcare", horizontal bcolor(blue)) ///
				(bar prob yaxis if phrase_order==4 & god==0 & topic=="healthcare", horizontal bcolor(eltblue)) ///
				(bar prob yaxis if phrase_order==4 & god==1 & topic=="healthcare", horizontal bcolor(blue)) ///
				(bar prob yaxis if phrase_order==5 & god==0 & topic=="healthcare", horizontal bcolor(eltblue)) ///
				(bar prob yaxis if phrase_order==5 & god==1 & topic=="healthcare", horizontal bcolor(blue)) ///
				(rcap prob_ub prob_lb yaxis if topic=="healthcare", horizontal lcolor(gs7)), ///
				ylabel( 1.5 "care_reform" 4.5 "care_cost" 7.5 "public_health" 10.5 "medic_care"  13.5 "health_care" , noticks labgap(*3)) ytitle("") ///
				  legend(order(2 `"Democrat "God" Speeches"' 1 "Other Democrat Speeches") size(vsmall)) xtitle("Phrase Probability (%)") title("Healthcare") name("healthcare", replace)

*topic graph: welfare
bro if topic=="welfare"
graph twoway	(bar prob yaxis if phrase_order==1 & god==0 & topic=="welfare", horizontal bcolor(eltblue)) ///
				(bar prob yaxis if phrase_order==1 & god==1 & topic=="welfare", horizontal bcolor(blue))  ///
				(bar prob yaxis if phrase_order==2 & god==0 & topic=="welfare", horizontal bcolor(eltblue)) ///
				(bar prob yaxis if phrase_order==2 & god==1 & topic=="welfare", horizontal bcolor(blue)) ///
				(bar prob yaxis if phrase_order==3 & god==0 & topic=="welfare", horizontal bcolor(eltblue)) ///
				(bar prob yaxis if phrase_order==3 & god==1 & topic=="welfare", horizontal bcolor(blue)) ///
				(bar prob yaxis if phrase_order==4 & god==0 & topic=="welfare", horizontal bcolor(eltblue)) ///
				(bar prob yaxis if phrase_order==4 & god==1 & topic=="welfare", horizontal bcolor(blue)) ///
				(bar prob yaxis if phrase_order==5 & god==0 & topic=="welfare", horizontal bcolor(eltblue)) ///
				(bar prob yaxis if phrase_order==5 & god==1 & topic=="welfare", horizontal bcolor(blue)) ///
				(rcap prob_ub prob_lb yaxis if topic=="welfare", horizontal lcolor(gs7)), ///
				ylabel( 1.5 "safeti_net" 4.5 "lose_job" 7.5 "poor_peopl" 10.5 "minimum_wage"  13.5 "social_secur" , noticks labgap(*3)) ytitle("") ///
				  legend(order(2 `"Democrat "God" Speeches"' 1 "Other Democrat Speeches") size(vsmall)) xtitle("Phrase Probability (%)") title("Welfare") name("welfare", replace)

*topic graph: education
bro if topic=="education"
graph twoway	(bar prob yaxis if phrase_order==1 & god==0 & topic=="education", horizontal bcolor(eltblue)) ///
				(bar prob yaxis if phrase_order==1 & god==1 & topic=="education", horizontal bcolor(blue))  ///
				(bar prob yaxis if phrase_order==2 & god==0 & topic=="education", horizontal bcolor(eltblue)) ///
				(bar prob yaxis if phrase_order==2 & god==1 & topic=="education", horizontal bcolor(blue)) ///
				(bar prob yaxis if phrase_order==3 & god==0 & topic=="education", horizontal bcolor(eltblue)) ///
				(bar prob yaxis if phrase_order==3 & god==1 & topic=="education", horizontal bcolor(blue)) ///
				(bar prob yaxis if phrase_order==4 & god==0 & topic=="education", horizontal bcolor(eltblue)) ///
				(bar prob yaxis if phrase_order==4 & god==1 & topic=="education", horizontal bcolor(blue)) ///
				(bar prob yaxis if phrase_order==5 & god==0 & topic=="education", horizontal bcolor(eltblue)) ///
				(bar prob yaxis if phrase_order==5 & god==1 & topic=="education", horizontal bcolor(blue)) ///
				(rcap prob_ub prob_lb yaxis if topic=="education", horizontal lcolor(gs7)), ///
				ylabel( 1.5 "student_loan" 4.5 "public_educ" 7.5 "educ_program" 10.5 "educ_opportun"  13.5 "public_school" , noticks labgap(*3)) ytitle("") ///
				  legend(order(2 `"Democrat "God" Speeches"' 1 "Other Democrat Speeches") size(vsmall)) xtitle("Phrase Probability (%)") title("Education") name("education", replace)
				 		 
*topic graph: civil_rights
bro if topic=="civil_rights"
graph twoway	(bar prob yaxis if phrase_order==1 & god==0 & topic=="civil_rights", horizontal bcolor(eltblue)) ///
				(bar prob yaxis if phrase_order==1 & god==1 & topic=="civil_rights", horizontal bcolor(blue))  ///
				(bar prob yaxis if phrase_order==2 & god==0 & topic=="civil_rights", horizontal bcolor(eltblue)) ///
				(bar prob yaxis if phrase_order==2 & god==1 & topic=="civil_rights", horizontal bcolor(blue)) ///
				(bar prob yaxis if phrase_order==3 & god==0 & topic=="civil_rights", horizontal bcolor(eltblue)) ///
				(bar prob yaxis if phrase_order==3 & god==1 & topic=="civil_rights", horizontal bcolor(blue)) ///
				(bar prob yaxis if phrase_order==4 & god==0 & topic=="civil_rights", horizontal bcolor(eltblue)) ///
				(bar prob yaxis if phrase_order==4 & god==1 & topic=="civil_rights", horizontal bcolor(blue)) ///
				(bar prob yaxis if phrase_order==5 & god==0 & topic=="civil_rights", horizontal bcolor(eltblue)) ///
				(bar prob yaxis if phrase_order==5 & god==1 & topic=="civil_rights", horizontal bcolor(blue)) ///
				(rcap prob_ub prob_lb yaxis if topic=="civil_rights", horizontal lcolor(gs7)), ///
				ylabel( 1.5 "equal_right" 4.5 "vote_right" 7.5 "equal_opportun" 10.5 "constitut_right"  13.5 "african_american" , noticks labgap(*3)) ytitle("") ///
				  legend(order(2 `"Democrat "God" Speeches"' 1 "Other Democrat Speeches") size(vsmall)) xtitle("Phrase Probability (%)") title("Civil Rights") name("civil_rights", replace)

*topic graph: environment
bro if topic=="environment"
format prob %9.0f
graph twoway	(bar prob yaxis if phrase_order==1 & god==0 & topic=="environment", horizontal bcolor(eltblue)) ///
				(bar prob yaxis if phrase_order==1 & god==1 & topic=="environment", horizontal bcolor(blue))  ///
				(bar prob yaxis if phrase_order==2 & god==0 & topic=="environment", horizontal bcolor(eltblue)) ///
				(bar prob yaxis if phrase_order==2 & god==1 & topic=="environment", horizontal bcolor(blue)) ///
				(bar prob yaxis if phrase_order==3 & god==0 & topic=="environment", horizontal bcolor(eltblue)) ///
				(bar prob yaxis if phrase_order==3 & god==1 & topic=="environment", horizontal bcolor(blue)) ///
				(bar prob yaxis if phrase_order==4 & god==0 & topic=="environment", horizontal bcolor(eltblue)) ///
				(bar prob yaxis if phrase_order==4 & god==1 & topic=="environment", horizontal bcolor(blue)) ///
				(bar prob yaxis if phrase_order==5 & god==0 & topic=="environment", horizontal bcolor(eltblue)) ///
				(bar prob yaxis if phrase_order==5 & god==1 & topic=="environment", horizontal bcolor(blue)) ///
				(rcap prob_ub prob_lb yaxis if topic=="environment", horizontal lcolor(gs7)), ///
				ylabel( 1.5 "climat_chang" 4.5 "environment_protect" 7.5 "clean_air" 10.5 "natur_disast"  13.5 "natur_resourc" , noticks labgap(*3)) ytitle("") ///
				  legend(order(2 `"Democrat "God" Speeches"' 1 "Other Democrat Speeches") size(vsmall)) xlabel(0(1)2) xtitle("Phrase Probability (%)") title("Environment") name("environment", replace)

*topic graph: nuclear
bro if topic=="nuclear"
format prob %9.1f
graph twoway	(bar prob yaxis if phrase_order==1 & god==0 & topic=="nuclear", horizontal bcolor(eltblue)) ///
				(bar prob yaxis if phrase_order==1 & god==1 & topic=="nuclear", horizontal bcolor(blue))  ///
				(bar prob yaxis if phrase_order==2 & god==0 & topic=="nuclear", horizontal bcolor(eltblue)) ///
				(bar prob yaxis if phrase_order==2 & god==1 & topic=="nuclear", horizontal bcolor(blue)) ///
				(bar prob yaxis if phrase_order==3 & god==0 & topic=="nuclear", horizontal bcolor(eltblue)) ///
				(bar prob yaxis if phrase_order==3 & god==1 & topic=="nuclear", horizontal bcolor(blue)) ///
				(bar prob yaxis if phrase_order==4 & god==0 & topic=="nuclear", horizontal bcolor(eltblue)) ///
				(bar prob yaxis if phrase_order==4 & god==1 & topic=="nuclear", horizontal bcolor(blue)) ///
				(bar prob yaxis if phrase_order==5 & god==0 & topic=="nuclear", horizontal bcolor(eltblue)) ///
				(bar prob yaxis if phrase_order==5 & god==1 & topic=="nuclear", horizontal bcolor(blue)) ///
				(rcap prob_ub prob_lb yaxis if topic=="nuclear", horizontal lcolor(gs7)), ///
				ylabel( 1.5 "nuclear_warhead" 4.5 "nuclear_arm" 7.5 "nuclear_test" 10.5 "atom_energi"  13.5 "nuclear_war" , noticks labgap(*3)) ytitle("") ///
				  legend(order(2 `"Democrat "God" Speeches"' 1 "Other Democrat Speeches") size(vsmall)) xtitle("Phrase Probability (%)") title("Nuclear") name("nuclear", replace)
				  
*topic graph: gun_control
bro if topic=="gun_control"
format prob %9.1f
graph twoway	(bar prob yaxis if phrase_order==1 & god==0 & topic=="gun_control", horizontal bcolor(eltblue)) ///
				(bar prob yaxis if phrase_order==1 & god==1 & topic=="gun_control", horizontal bcolor(blue))  ///
				(bar prob yaxis if phrase_order==2 & god==0 & topic=="gun_control", horizontal bcolor(eltblue)) ///
				(bar prob yaxis if phrase_order==2 & god==1 & topic=="gun_control", horizontal bcolor(blue)) ///
				(bar prob yaxis if phrase_order==3 & god==0 & topic=="gun_control", horizontal bcolor(eltblue)) ///
				(bar prob yaxis if phrase_order==3 & god==1 & topic=="gun_control", horizontal bcolor(blue)) ///
				(bar prob yaxis if phrase_order==4 & god==0 & topic=="gun_control", horizontal bcolor(eltblue)) ///
				(bar prob yaxis if phrase_order==4 & god==1 & topic=="gun_control", horizontal bcolor(blue)) ///
				(bar prob yaxis if phrase_order==5 & god==0 & topic=="gun_control", horizontal bcolor(eltblue)) ///
				(bar prob yaxis if phrase_order==5 & god==1 & topic=="gun_control", horizontal bcolor(blue)) ///
				(rcap prob_ub prob_lb yaxis if topic=="gun_control", horizontal lcolor(gs7)), ///
				ylabel( 1.5 "buy_gun" 4.5 "gun_violenc" 7.5 "gun_control" 10.5 "assault_weapon"  13.5 "arm_control" , noticks labgap(*3)) ytitle("") ///
				  legend(order(2 `"Democrat "God" Speeches"' 1 "Other Democrat Speeches") size(vsmall)) xtitle("Phrase Probability (%)") title("Gun Control") name("gun_control", replace)
				  
				  				  
*graph options (choose 6 from these in this order): healthcare welfare education civil_rights environment nuclear gun_control
grc1leg healthcare welfare education civil_rights environment gun_control, col(3) name(dem_phrase_probs, replace)

*save graph 
graph export dem_phrase_probs.eps, name(dem_phrase_probs) replace
graph drop healthcare welfare education civil_rights environment nuclear gun_control
							  
			